micronaut:
  application:
    name: bachelorarbeit_Micronaut
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
datasources:
  default:
    url: jdbc:postgresql://172.16.180.38:5432/Micronaut
    #url: jdbc:postgresql://192.168.2.110/Micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: org.hibernate.dialect.PostgreSQLDialect
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update