micronaut:
  application:
    name: bachelorarbeit_Micronaut
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
datasources:
  default:
    #url: jdbc:h2:mem:devDb
    #url: jdbc:h2:file:C:/dockerVolume/MicronautDB
    url: jdbc:postgresql://localhost:5432/Micronaut
    #driverClassName: org.h2.Driver
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    #dialect: H2
    dialect: org.hibernate.dialect.PostgreSQLDialect
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update